name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  testAndRelease:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Prepare env
      run: go get .

    - name: Test
      run: go test -v ./...

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v6
      with:
        distribution: goreleaser
        version: '~> v2'
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
